service: microservice-streaming

frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  timeout: 30

plugins:
  - serverless-dotenv-plugin # Allow set global parameters in env.{enviroment}
  - serverless-offline

functions:
  findAllSessions:
    handler: gatways/routes/main.handle
    events:
      - http:
          path: /{controller}/{action}
          method: get
          cors: true
          request:
          parameters:
            paths:
              action: true
              controller: true
  paginationSessions:
    handler: gatways/routes/main.handle
    events:
      - http:
          path: /{controller}/{action}/{page}
          method: get
          cors: true
          request:
          parameters:
            paths:
              action: true
              controller: true
  createSession:
    handler: gatways/routes/main.handle
    events:
      - http:
          path: /{controller}/{action}/
          method: post
          cors: true
          request:
          parameters:
            paths:
              action: true
              controller: true
